GET http://localhost:8080/mechanic
Accept: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA

###

PUT http://localhost:8080/mechanic/qualify
Accept: application/json
Content-Type: application/json

{
"idUser": 1,
"idMechanic": 1,
"score": 5
}

###

GET http://localhost:8080/mechanic/seller
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ

###

PUT http://localhost:8080/mechanic/paymentPlan?idPlan=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA


###
GET http://localhost:8080/mechanic/adm/mechanics?n=1&i=0&search=sho
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ
###
GET http://localhost:8080/mechanic/adm/mechanicShop?n=10&i=0
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ
###
PUT http://localhost:8080/mechanic/status?status=1&idSeller=33
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ
###
PUT http://localhost:8080/mechanic
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ

{
  "idMechanic": 4,
  "idCity": 2,
  "location": "Miraflores",
  "shopName": "Rapidos",
  "shopPhoneNumber": "123456",
  "status": 1
}
###