
###
GET http://localhost:8080/paymentPlan
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA