GET http://localhost:8080/publications/?n=5&i=0
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/publications/idd?idPublication=4
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/publications/paths?idPublication=4
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/publications/colors
Accept: application/json
Content-Type: application/json


###

POST http://localhost:8080/publications
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA

{
  "idBrand": 1,
  "idColor": 1,
  "idCity": 1,
  "idPlan": 2,
  "title": "Title 6",
  "model": 2018,
  "doorNumber": 5,
  "licensePlate": "4089ZPLP",
  "description": "Hermoso auto con todas las prestaciones y confort",
  "motor": "1600cc",
  "price": 15000.500
}

###

DELETE http://localhost:8080/publications?idPublication=1
Accept: application/json


###

PUT http://localhost:8080/publications/paymentPlan1?idPlan=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA

###

PUT http://localhost:8080/publications
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjEsImlkU2VsbGVyIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIwNTExMTYyLCJleHAiOjE2MjA1OTc1NjJ9.euLznRaKFmMXR0KbnR84WblslW-QLPcf3tFWiwFLqt64IDoqFyXCRWWY5FhkkBZjJYPpHmLajf5N6Ma6IJGOmA

{
  "idPublication": 261,
  "idSeller": 1,
  "idBrand": 3,
  "idColor": 4,
  "idCity": 2,
  "idPlan": null,
  "title": "Title 6",
  "model": 2018,
  "doorNumber": 5,
  "licensePlate": "4089ZPLP",
  "description": "Hermoso auto con todas las prestaciones y confort",
  "motor": "1600cc",
  "price": 15000.500
}

