POST http://localhost:8080/user/signin/Admi
Accept: application/json
Content-Type: application/json

{
  "email": "afussey11@wordpress.org",
  "password": "abc1234"
}

###

GET http://localhost:8080/seller
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjM4LCJpZFNlbGxlciI6MzgsImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMTg0Nzk4LCJleHAiOjE2MjEyNzExOTh9._PpJkGP_2yVK1qs-TErEQJ_SavDZGOEr-4vqYw67v-FjNO5XqR4OkFLOL-CWaDT__L4WPQR0lnE0Rp6lYc_apg

###

POST http://localhost:8080/seller
Accept: application/json
Content-Type: application/json

{
  "idSeller": 1,
  "idPerson": 1,
  "idUser": 1,
  "password": "12345",
  "email": "456985",
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321",
  "imagePath": "Hermoso auto con todas las prestaciones y confort"
}

###

PUT http://localhost:8080/seller/image
Accept: application/json
Content-Type: application/json

{
"idSeller": 4
}

###

PUT http://localhost:8080/seller
Accept: application/json
Content-Type: application/json

{
  "idSeller": 1,
  "idPerson": 1,
  "idUser": 1,
  "password": "1234abc",
  "email": "erwin@gmail.com",
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321",
  "imagePath": "hello.com"
}

###
GET http://localhost:8080/seller/publications?i=0&n=10
Accept: application/json


###
GET http://localhost:8080/seller/idSeller=1
Accept: application/json

###
POST http://localhost:8080/user
Accept: application/json
Content-Type: application/json

{
  "idSeller": 512,
  "idPerson": 512,
  "idUser": 512,
  "password": "12345",
  "email": "456985",
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321",
  "imagePath": "Hermoso auto con todas las prestaciones y confort"
}

###
GET http://localhost:8080/seller/users?n=10&i=0&search=than
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ

###
DELETE http://localhost:8080/seller?idUser=45
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZFVzZXIiOjE5LCJpZFNlbGxlciI6MTksImFsZyI6IkhTNTEyIn0.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjIxMzYwNTgyLCJleHAiOjE2MjE0NDY5ODJ9.4k7xSFm4IwihQ68vkWiNFw2ZCu8A12So58nvnMgEK22S3hwHAs-gu9pgq4dh6UYSzm4yLL9M6uC9uOROqytOQQ

###
